### ISSUE TITLE
Further guidance required for example. 

### ISSUE THREAD

**Issue by UX-Writer-Debbie** [MicrosoftDocs/microsoft-style-guide#422] opened 2023-10-25 07:10 UTC
[Enter feedback here]
The example "A variety of games is available from Microsoft Store" is contentious and needs further explanation. The plural form is the most natural sounding and preferred verb conjugation. Plus [Collins dictionary](https://www.collinsdictionary.com/dictionary/english/variety#:~:text=As%20a%20collective%20noun%2C%20variety,See%20also%20collective%20noun%2C%20number.) states that "a variety " is plural while "the variety" is singular. The example should be updated or guidance should be clarified to avoid ambiguity. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e98fcd08-8edf-0a1d-2a62-6d827bc327b9
* Version Independent ID: d1ca993e-79e8-5373-44f4-c7390a736bfe
* Content: [Verbs - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/grammar/verbs)
* Content Source: [styleguide/grammar/verbs.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/grammar/verbs.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment] 2023-11-02 15:44
Thanks for the feedback, @UX-Writer-Debbie - we'll look into it.

**Comment by Jay-o-Way** [comment] 2023-11-16 23:00
Duplicate of #399

**Closed** 2024-01-29 16:07 UTC
